import React, { useEffect, useMemo, useState, type FormEvent } from "react";
import L from "leaflet";
import "leaflet/dist/leaflet.css";
import { citySummaryForDate, recordForWard } from "../data/historicalRisk";
import { puneHeatTrend } from "../data/mockHeatTrend";
import { heatLocalities } from "../data/mockHeatLocalities";
import { thermalMetrics } from "../data/thermalStress";
import type { RiskLevel } from "../types/heat";
import type { CitizenProfile } from "../citizenAuth";

type View = "home" | "risk" | "map" | "forecast" | "centres" | "navigation" | "alerts" | "hydration" | "solar" | "report" | "profile";
type Props = { profile: CitizenProfile; onProfile: (profile: CitizenProfile) => void; onSignOut: () => void };
const views: View[] = ["home", "risk", "map", "forecast", "centres", "navigation", "alerts", "hydration", "solar", "report", "profile"];
const riskClass = (risk: RiskLevel) => `risk-${risk.toLowerCase().replaceAll(" ", "-")}`;
const today = "2026-09-01";
const centres = [{ name: "PMC cooling support point · Shivajinagar", address: "Shivajinagar, Pune", latitude: 18.5304, longitude: 73.8493 }, { name: "PMC cooling support point · Hadapsar", address: "Hadapsar, Pune", latitude: 18.5089, longitude: 73.9259 }, { name: "PMC cooling support point · Kothrud", address: "Kothrud, Pune", latitude: 18.5074, longitude: 73.8077 }];

function Icon({ name }: { name: string }) { const icons: Record<string, string> = { home: "M3 11l9-8 9 8v10h-6v-6H9v6H3z", heat: "M12 2c3 4 6 6 6 11a6 6 0 1 1-12 0c0-5 3-7 6-11z", map: "m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3zM9 3v15m6-12v15", chart: "M3 3v18h18M7 16l4-5 3 2 5-7", pin: "M12 22s7-6.1 7-12a7 7 0 1 0-14 0c0 5.9 7 12 7 12zM12 12.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z", route: "M6 3h4v4H6zM14 17h4v4h-4zM8 7c0 6 8 2 8 10", bell: "M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9", water: "M12 2s6 6.1 6 11a6 6 0 1 1-12 0c0-4.9 6-11 6-11z", sun: "M12 3v2m0 14v2m9-9h-2M5 12H3m15.4-6.4-1.4 1.4M7 17l-1.4 1.4m12.8 0L17 17M7 7 5.6 5.6M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0z", report: "M6 3h9l3 3v15H6zM9 12h6m-6 4h6", user: "M20 21a8 8 0 0 0-16 0M12 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8", menu: "M4 7h16M4 12h16M4 17h16", phone: "M7.5 3.5 5.1 5.2c-.75.54-.98 1.54-.54 2.35 2.5 4.61 6.29 8.4 10.9 10.9.81.44 1.81.21 2.35-.54l1.69-2.4a1.75 1.75 0 0 0-.35-2.36l-2.25-1.76a1.75 1.75 0 0 0-2.34.1l-1.34 1.3a12.9 12.9 0 0 1-2.01-2.01l1.3-1.34a1.75 1.75 0 0 0 .1-2.34L9.86 3.85a1.75 1.75 0 0 0-2.36-.35Z" }; return <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={icons[name]} /></svg>; }
function Tag({ risk }: { risk: RiskLevel }) { return <span className={`risk-label ${riskClass(risk)} citizen-tag`}>{risk}</span>; }
function Intro({ title, detail }: { title: string; detail: string }) { return <div className="citizen-intro"><p>SAAYA · Pune Heat Health</p><h1>{title}</h1><span>{detail}</span></div>; }

function CitizenMap({ selectedLocality, showCentres = false }: { selectedLocality: string; showCentres?: boolean }) { const [node, setNode] = useState<HTMLDivElement | null>(null); useEffect(() => { if (!node) return; const local = heatLocalities.find((item) => item.locality === selectedLocality) ?? heatLocalities[8]; const map = L.map(node, { scrollWheelZoom: true }).setView([local.latitude, local.longitude], 12); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { attribution: "© OpenStreetMap" }).addTo(map); const wardRisks = new Map(citySummaryForDate(today).rows.map((row) => [row.wardId, row.riskLevel])); const colors: Record<RiskLevel, string> = { Low: "#257451", Moderate: "#b67a13", High: "#ca5a1d", "Very High": "#b73335", Extreme: "#68233f" }; void fetch("/data/pune-electoral-wards-2022.geojson").then((response) => response.json()).then((geojson: GeoJSON.FeatureCollection<GeoJSON.Geometry, { wardnum: number }>) => L.geoJSON(geojson, { style: (feature) => ({ color: "#fff", weight: .7, fillColor: colors[wardRisks.get(feature?.properties.wardnum) ?? "Low"], fillOpacity: .46 }) }).addTo(map)).catch(() => undefined); heatLocalities.forEach((place) => L.circleMarker([place.latitude, place.longitude], { radius: 7, color: "#fff", weight: 1, fillColor: colors[place.thermalRisk], fillOpacity: .85 }).bindPopup(`<b>${place.locality}</b><br>${place.thermalRisk} heat risk`).addTo(map)); L.marker([local.latitude, local.longitude]).bindPopup("You are here / selected locality").addTo(map).openPopup(); if (showCentres) centres.forEach((centre) => L.marker([centre.latitude, centre.longitude]).bindPopup(`<b>${centre.name}</b><br>${centre.address}<br>Information unavailable`).addTo(map)); return () => { map.remove(); }; }, [node, selectedLocality, showCentres]); return <div ref={setNode} className="saaya-leaflet citizen-map" aria-label="Interactive Pune heat map" />; }

function CitizenSidebar({ view, navigate, collapsed, toggle }: { view: View; navigate: (view: View) => void; collapsed: boolean; toggle: () => void }) { const [open, setOpen] = useState<Record<string, boolean>>({ heat: true, safety: true, health: false, account: false }); const groups = [{ id: "heat", icon: "heat", label: "MY HEAT", entries: [["heat", "My Heat Risk", "risk"], ["map", "Heat Map", "map"], ["chart", "Forecast", "forecast"]] }, { id: "safety", icon: "pin", label: "SAFETY & RESOURCES", entries: [["pin", "Cooling Centres", "centres"], ["route", "Thermal Navigation", "navigation"], ["bell", "Alerts", "alerts"]] }, { id: "health", icon: "water", label: "HEALTH", entries: [["water", "Hydration", "hydration"], ["sun", "Sun / Solar Intensity", "solar"]] }, { id: "account", icon: "user", label: "MY ACCOUNT", entries: [["user", "My Profile", "profile"]] }]; const item = (icon: string, label: string, target: View) => <button key={target} title={collapsed ? label : undefined} onClick={() => navigate(target)} className={`citizen-nav-item ${view === target ? "is-active" : ""}`}><Icon name={icon} /><span>{label}</span></button>; return <aside className={`citizen-sidebar ${collapsed ? "is-collapsed" : ""}`}><div className="citizen-brand"><div><b>साया</b><span>Your Heat Health Companion</span></div><button title={collapsed ? "Expand sidebar" : "Collapse sidebar"} onClick={toggle}><Icon name="menu" /></button></div><nav>{item("home", "Home / Overview", "home")}{groups.map((group) => <div className="citizen-nav-group" key={group.id}><button title={collapsed ? group.label : undefined} className="citizen-group-toggle" onClick={() => setOpen((current) => ({ ...current, [group.id]: !current[group.id] }))}><Icon name={group.icon}/><span>{group.label}</span><b>{open[group.id] ? "⌄" : "›"}</b></button>{open[group.id] && <div>{group.entries.map(([icon, label, target]) => item(icon, label, target as View))}</div>}</div>)}{item("report", "Report an Incident", "report")}</nav><a className="citizen-emergency" href="tel:108" title="Emergency Help · 108"><Icon name="phone" /><span><b>Emergency Help</b><strong>108</strong></span></a></aside>; }

export function CitizenPortal({ profile, onProfile, onSignOut }: Props) { const [collapsed, setCollapsed] = useState(false); const [view, setView] = useState<View>(() => { const value = window.location.hash.replace("#citizen/", "") as View; return views.includes(value) ? value : "home"; }); const navigate = (next: View) => { window.history.pushState({}, "", `#citizen/${next}`); setView(next); window.scrollTo({ top: 0 }); }; useEffect(() => { const pop = () => { const value = window.location.hash.replace("#citizen/", "") as View; setView(views.includes(value) ? value : "home"); }; window.addEventListener("popstate", pop); return () => window.removeEventListener("popstate", pop); }, []); const locality = useMemo(() => heatLocalities.find((place) => place.locality === profile.locality) ?? heatLocalities[8], [profile.locality]); const summary = citySummaryForDate(today); const ward = recordForWard(today, 1) ?? summary.rows[0]; const metrics = thermalMetrics(ward); const content = <CitizenContent view={view} profile={profile} onProfile={onProfile} locality={locality} summary={summary} metrics={metrics} navigate={navigate} />; return <div className="citizen-shell"><CitizenSidebar view={view} navigate={navigate} collapsed={collapsed} toggle={() => setCollapsed((value) => !value)} /><main className={`citizen-content ${collapsed ? "sidebar-collapsed" : ""}`}><header className="citizen-header"><div><b>SAAYA</b><span>Your Heat Health Companion · Pune</span></div><div><span>{profile.name}</span><button onClick={onSignOut}>Sign out</button></div></header>{content}</main></div>; }

function CitizenContent({ view, profile, onProfile, locality, summary, metrics, navigate }: { view: View; profile: CitizenProfile; onProfile: (profile: CitizenProfile) => void; locality: typeof heatLocalities[number]; summary: ReturnType<typeof citySummaryForDate>; metrics: ReturnType<typeof thermalMetrics>; navigate: (view: View) => void }) { const recommendation = profile.outdoorWorker && summary.riskLevel !== "Low" ? "Your work may involve prolonged outdoor exposure. Consider reducing exposure during the afternoon peak where possible." : "Plan outdoor activity outside the 12 PM–4 PM peak heat period where possible."; if (view === "home") return <section className="citizen-page"><Intro title="How risky is the heat around me?" detail={`Local conditions for ${profile.locality}.`}/><section className="citizen-hero"><div><p>Current heat risk</p><h2 className={riskClass(locality.thermalRisk)}>{locality.thermalRisk}</h2><b>{summary.score} / 100 heat-risk score</b><span>Current municipal advisory: monitor heat exposure from 12 PM–4 PM.</span></div><dl><div><dt>Temperature</dt><dd>{locality.temperature}°C</dd></div><div><dt>Humidity</dt><dd>{locality.humidity}%</dd></div><div><dt>Wind</dt><dd>{locality.windSpeed} km/h</dd></div><div><dt>Nearby centres</dt><dd>3 listed</dd></div></dl></section><section className="citizen-quick"><button onClick={() => navigate("map")}><Icon name="map" />Heat Map</button><button onClick={() => navigate("centres")}><Icon name="pin" />Cooling Centres</button><button onClick={() => navigate("forecast")}><Icon name="chart" />Forecast</button></section><section className="citizen-note"><b>Personal guidance</b><p>{recommendation}</p>{locality.thermalRisk === "Very High" || locality.thermalRisk === "Extreme" ? <a href="tel:108">Need urgent help? Call 108.</a> : null}</section></section>;
  if (view === "risk") return <section className="citizen-page"><Intro title="Your current heat risk" detail="Based on the shared Pune ward heat-intelligence model and your selected locality."/><section className="risk-detail"><div><Tag risk={locality.thermalRisk}/><h2>{summary.score} <small>/ 100</small></h2><p>{profile.locationPermission ? "Current location enabled" : `Residential locality · ${profile.locality}`}</p></div><dl><div><dt>Temperature</dt><dd>{locality.temperature}°C</dd></div><div><dt>Humidity</dt><dd>{locality.humidity}%</dd></div><div><dt>Wind</dt><dd>{locality.windSpeed} km/h</dd></div><div><dt>Screening WBGT</dt><dd>{metrics.wbgt.toFixed(1)}°C</dd></div><div><dt>Above seasonal normal</dt><dd>+5°C</dd></div></dl></section><section className="citizen-note"><b>Why</b><p>{metrics.explanation} This is a shared modelled heat-risk indication, not a medical assessment.</p></section></section>;
  if (view === "map") return <section className="citizen-page"><Intro title="Pune heat map" detail="Ward and locality heat-risk zones use the same municipal risk categories and underlying calculation."/><CitizenMap selectedLocality={profile.locality}/><p className="map-disclaimer">“You are here” marks your selected locality. Precise device location is only used when you grant permission. Green: Low · Amber: Moderate · Orange: High · Red: Very High · Maroon: Extreme.</p></section>;
  if (view === "forecast") return <section className="citizen-page"><Intro title="Heat forecast" detail="Simulated municipal outlook; it is not a live weather forecast."/><div className="forecast-list">{puneHeatTrend.filter((day) => day.period === "Forecast").slice(0, 5).map((day) => <article key={day.date}><div><b>{day.weekday} · {day.label}</b><span>Max {day.maxTemperature}°C · Min {day.minTemperature}°C</span></div><div><span>Humidity {day.humidity}% · Wind {day.windSpeed} km/h</span><Tag risk={day.risk}/></div><p>{day.score}/100 · {day.recommendedAction}</p></article>)}</div></section>;
  if (view === "centres") return <section className="citizen-page"><Intro title="Cooling centres" detail="Prototype municipal support directory. Confirm availability before travelling."/><CitizenMap selectedLocality={profile.locality} showCentres/><div className="centre-list">{centres.map((centre, index) => <article key={centre.name}><div><h2>{centre.name}</h2><p>{centre.address} · {(0.8 + index * .7).toFixed(1)} km away</p></div><dl><div><dt>Hours</dt><dd>Information unavailable</dd></div><div><dt>Facilities</dt><dd>Information unavailable</dd></div><div><dt>Accessibility</dt><dd>Information unavailable</dd></div></dl><a href={`https://www.openstreetmap.org/?mlat=${centre.latitude}&mlon=${centre.longitude}#map=15/${centre.latitude}/${centre.longitude}`} target="_blank" rel="noreferrer">Get directions</a></article>)}</div></section>;
  if (view === "navigation") return <Navigation locality={profile.locality} risk={locality.thermalRisk}/>;
  if (view === "alerts") return <section className="citizen-page"><Intro title="Municipal heat alerts" detail="Alerts are shown for your selected locality and shared municipal risk data."/><section className="alert-card"><Tag risk={locality.thermalRisk}/><h2>{locality.thermalRisk.toUpperCase()} HEAT ALERT</h2><p>Your area is expected to experience elevated thermal stress today, especially between <b>12 PM – 4 PM</b>.</p><ul><li>Avoid prolonged outdoor exposure.</li><li>Drink water regularly and rest in shaded or cool places.</li><li>Use a cooling centre if you need relief.</li></ul></section><p className="map-disclaimer">Admin-created alerts will appear here when connected to the municipal alert service. This prototype currently shows the shared model-triggered advisory.</p></section>;
  if (view === "hydration") return <Hydration/>;
  if (view === "solar") return <section className="citizen-page"><Intro title="Solar intensity" detail="Solar radiation from the municipal thermal dataset; this is not UV Index."/><section className="solar-layout"><div className="solar-gauge"><div style={{ "--value": `${Math.min(100, Math.round((metrics.contributors.find((item) => item.label === "Solar radiation")?.value ?? 0)))}%` } as React.CSSProperties}><b>{wardSolar(metrics)}%</b><span>Solar intensity</span></div></div><div><Tag risk={metrics.thermalStress}/><h2>High solar intensity</h2><p>Peak exposure period: 12 PM – 3 PM</p><p>Prefer shade, cover exposed skin and plan outdoor journeys outside peak sun where possible.</p></div></section></section>;
  if (view === "report") return <Report profile={profile}/>;
  return <Profile profile={profile} onProfile={onProfile}/>;
}
function wardSolar(metrics: ReturnType<typeof thermalMetrics>) { return Math.min(100, Math.round(metrics.contributors.find((item) => item.label === "Solar radiation")?.value ?? 0)); }
function Navigation({ locality, risk }: { locality: string; risk: RiskLevel }) { const [from, setFrom] = useState(locality), [to, setTo] = useState("Shivajinagar"); return <section className="citizen-page"><Intro title="Thermal navigation" detail="Prototype route comparison based on available locality and ward-level heat risk; no street-level shade or real-time temperature data is claimed."/><section className="route-form"><label>Starting location<select value={from} onChange={(e) => setFrom(e.target.value)}>{heatLocalities.map((item) => <option key={item.locality}>{item.locality}</option>)}</select></label><label>Destination<select value={to} onChange={(e) => setTo(e.target.value)}>{heatLocalities.map((item) => <option key={item.locality}>{item.locality}</option>)}</select></label></section><div className="route-options"><article><p>Fastest route</p><h2>18 min · 5.2 km</h2><Tag risk={risk}/><span>Estimated exposure uses route-area risk.</span></article><article className="recommended"><p>Recommended · coolest route</p><h2>21 min · 5.5 km</h2><Tag risk="Moderate"/><span>Lower estimated exposure; 3 minutes longer.</span></article></div></section>; }
function Hydration() { const [amount, setAmount] = useState(0), [enabled, setEnabled] = useState(true), [frequency, setFrequency] = useState("Every 2 hours"); return <section className="citizen-page"><Intro title="Hydration check" detail="A simple reminder and personal tracking tool, not a medically precise hydration prescription."/><section className="hydration-card"><div><p>Daily progress</p><h2>{amount} <small>glasses recorded</small></h2><div className="water-progress"><span style={{ width: `${Math.min(100, amount / 8 * 100)}%` }}/></div><p>{amount >= 6 ? "You’re keeping up well." : "Time for some water."}</p></div><button onClick={() => setAmount((value) => value + 1)}>Record a glass of water</button></section><section className="citizen-settings"><label>Water reminders<select value={frequency} onChange={(e) => setFrequency(e.target.value)}><option>Every hour</option><option>Every 2 hours</option><option>Every 3 hours</option></select></label><label className="toggle-line">Enable reminders<button aria-pressed={enabled} onClick={() => setEnabled((value) => !value)}>{enabled ? "On" : "Off"}</button></label></section></section>; }
function Report({ profile }: { profile: CitizenProfile }) { const [submitted, setSubmitted] = useState(false), [type, setType] = useState("Heat illness/emergency"), [description, setDescription] = useState(""), [location, setLocation] = useState(profile.locality); const submit = (e: FormEvent) => { e.preventDefault(); if (description.trim()) setSubmitted(true); }; return <section className="citizen-page"><Intro title="Report an incident" detail="Reports are structured for the municipal portal to receive in a future connected service."/>{submitted ? <section className="confirmation"><h2>Report received</h2><p>Thank you. Your {type.toLowerCase()} report for {location} has been recorded in this prototype.</p><button onClick={() => setSubmitted(false)}>Submit another report</button></section> : <form className="citizen-form" onSubmit={submit}><label>Incident type<select value={type} onChange={(e) => setType(e.target.value)}>{["Heat illness/emergency", "No drinking water", "Cooling centre issue", "Excessive heat in public area", "Water shortage", "Heat-related infrastructure issue", "Other"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Description<textarea required value={description} onChange={(e) => setDescription(e.target.value)} /></label><label>Location<input value={location} onChange={(e) => setLocation(e.target.value)} /></label><label>Optional photo<input type="file" accept="image/*" /></label>{profile.locationPermission && <p className="map-disclaimer">Your enabled location may be attached when the reporting service is connected.</p>}<button type="submit">Submit report</button></form>}</section>; }
function Profile({ profile, onProfile }: { profile: CitizenProfile; onProfile: (profile: CitizenProfile) => void }) { const [editing, setEditing] = useState(false), [draft, setDraft] = useState(profile); const save = () => { onProfile(draft); setEditing(false); }; return <section className="citizen-page"><Intro title="My profile" detail="This information helps SAAYA personalise local guidance. No medical information is collected."/><div className="profile-card">{([['Full name','name'],['Mobile number','mobile'],['Email','email'],['Residential locality','locality'],['Occupation','occupation'],['Outdoor-worker status','outdoorWorker'],['Age group','ageGroup'],['Preferred language','language'],['Emergency contact','emergencyContact']] as const).map(([label, key]) => <label key={key}><span>{label}</span>{editing ? key === 'locality' ? <select value={String(draft[key] ?? '')} onChange={(e) => setDraft({ ...draft, locality: e.target.value })}>{heatLocalities.map((item) => <option key={item.locality}>{item.locality}</option>)}</select> : key === 'outdoorWorker' ? <input type="checkbox" checked={Boolean(draft[key])} onChange={(e) => setDraft({ ...draft, outdoorWorker: e.target.checked })}/> : <input value={String(draft[key] ?? '')} onChange={(e) => setDraft({ ...draft, [key]: e.target.value })}/> : <b>{key === 'outdoorWorker' ? (profile.outdoorWorker ? 'Yes' : 'Not provided') : String(profile[key] ?? 'Not provided')}</b>}</label>)}<label><span>Location permission</span>{editing ? <input type="checkbox" checked={draft.locationPermission} onChange={(e) => setDraft({ ...draft, locationPermission: e.target.checked })}/> : <b>{profile.locationPermission ? 'Enabled' : 'Not enabled'}</b>}</label></div><button className="profile-edit" onClick={() => editing ? save() : setEditing(true)}>{editing ? 'Save profile' : 'Edit profile'}</button></section>; }
